### ISSUE TITLE
gmsc dont have executive permission by default

### ISSUE THREAD

**Issue by 1NO-NAME1** [adrianmmiller/GMSDozeSimplified#1]
![1](https://user-images.githubusercontent.com/97385339/216742494-52f1fafc-fea0-46f3-80a2-7f5637382cf7.jpg)

**Comment by adrianmmiller** [comment]
If you look at customize.sh, you'll see that the permissions are set correctly, for **/system/bin/gmsc**

Because you apparently have a system with xbin, the MMT-EXT magisk module logic first checks to see if /system/xbin exists and copies gmsc there, otherwise it goes to /system/bin....and it doesnt change the customize.sh line accordingly....

Its an oversight, and makes complete sense,  but i cant say ive ever had a report about this before, but theres always ONE of you people :)

Ive tried adding an extra line to the module for /system/xbin/gmsc, and updated the zip now...please test and report back if successful, thanks

p.s. apologies for late reply, but i hadnt meant for the repo to be used yet, and therefore hadnt been monitoring email notifications from it - they are now routed to my primary address...

**Comment by 1NO-NAME1** [comment]
Its now work correctly,thank for the work you done

**Comment by adrianmmiller** [comment]
No worries!

Have a great weekend
